import type { DiagnosisReportData } from '@/lib/api';

/**
 * PDF diagnosis report.
 *
 * Ported from the previous utils/generateReport.js with identical layout and
 * output, with one change: jsPDF is imported dynamically. It is ~350 KB and was
 * previously pulled into the main bundle for every visitor, including those who
 * never opened Diagnosis. Now it is fetched only when a report is downloaded.
 */

const SECTIONS: { key: keyof DiagnosisReportData; label: string }[] = [
  { key: 'crop_identified', label: 'Crop Identified' },
  { key: 'disease_identified', label: 'Disease Identified' },
  { key: 'disease_overview', label: 'Disease Overview' },
  { key: 'symptoms', label: 'Symptoms' },
  { key: 'causes', label: 'Causes' },
  { key: 'severity', label: 'Severity' },
  { key: 'immediate_steps', label: 'Immediate Steps' },
  { key: 'treatment', label: 'Treatment' },
  { key: 'prevention', label: 'Prevention' },
  { key: 'possible_impact', label: 'Possible Impact' },
  { key: 'monitoring_advice', label: 'Monitoring Advice' },
];

export async function generateReportPdf(
  reportData: DiagnosisReportData,
  cropName: string,
  diseaseName: string,
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF('p', 'mm', 'a4');

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 20;
  const marginRight = 20;
  const marginTop = 20;
  const marginBottom = 20;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let y = marginTop;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - marginBottom) {
      doc.addPage();
      y = marginTop;
    }
  };

  // Header band
  const headerHeight = 22;
  doc.setFillColor(26, 92, 42);
  doc.rect(0, 0, pageWidth, headerHeight, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('TerraMind', marginLeft, 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Smarter Farming Every Stage', marginLeft, 16);

  y = headerHeight + 8;

  const now = new Date();
  const dateStr = `${now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })}, ${now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;

  doc.setFontSize(9);
  doc.setTextColor(136, 136, 136);
  doc.text(`Report generated: ${dateStr}`, pageWidth - marginRight, y, { align: 'right' });
  y += 4;

  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 6;

  for (const section of SECTIONS) {
    const content = reportData[section.key] || 'N/A';

    ensureSpace(14);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(26, 92, 42);
    doc.text(section.label, marginLeft, y);
    y += 1.5;

    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.3);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(17, 17, 17);
    const lines = doc.splitTextToSize(content, contentWidth) as string[];

    for (const line of lines) {
      ensureSpace(5);
      doc.text(line, marginLeft, y);
      y += 4.5;
    }

    y += 6;
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(136, 136, 136);
    doc.text(
      'Generated by TerraMind | Confidential Agricultural Report',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' },
    );
  }

  const safeCrop = (cropName || 'Unknown').replace(/\s+/g, '_');
  const safeDisease = (diseaseName || 'Unknown')
    .replace(/_{2,}/g, '_')
    .replace(/\s+/g, '_');
  const dateTag =
    now.getFullYear().toString() +
    String(now.getMonth() + 1).padStart(2, '0') +
    String(now.getDate()).padStart(2, '0');

  doc.save(`TerraMind_Report_${safeCrop}_${safeDisease}_${dateTag}.pdf`);
}

export { SECTIONS as REPORT_SECTIONS };
